hw1 PR
martynovvladislav/tinkoff-java-backend-course-2024 pull request #1
Opened 2024-02-16 07:21 UTC by martynovvladislav

Сделан основной шаблон бота с командами (пока что заглушки), добавлено меню с командами, как у BotFather

2024-03-07 15:49 UTC, edikgoose requested changes
Сделано все аккуратно и хорошо. Поправь мелкие замечания и будет все отлично.
Задание сделано, тесты есть, бонус есть
9/9

2024-03-07 15:49 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/commands/HelpCommand.java
> +    public HelpCommand(TrackCommand trackCommand, UntrackCommand untrackCommand, ListCommand listCommand) {
спринг умеет сразу инжектить списком. То есть можешь написать List<? extends Command> commands и он по красоте все сделает)

2024-03-07 15:49 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/commands/StartCommand.java
> +    private final List<Command> commands;
А зачем он здесь?

2024-03-07 15:49 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/processors/MessageProcessor.java
> +            .stream()
где-то стрим переносишь, где-то нет. Лучше в одно стиле пиши)

2024-03-07 15:49 UTC, edikgoose commented on bot/src/test/java/edu/java/bot/commands/TestsForStartCommand.java
> +        Assertions.assertEquals(
Для читаемости можешь оставлять пустые строки между логическими действиями. То есть промокировал запросы, пустая строка, далее сделал запрос, снова пустая строка и тд.

2024-03-07 15:49 UTC, edikgoose commented on bot/src/test/java/edu/java/bot/commands/TestsForListCommand.java
> +        update = Mockito.mock(Update.class);
Эта логика в трех классах повторяется, можно в один абстрактный вынести

2024-03-08 12:10 UTC, martynovvladislav commented on bot/src/main/java/edu/java/bot/commands/HelpCommand.java
> +    public HelpCommand(TrackCommand trackCommand, UntrackCommand untrackCommand, ListCommand listCommand) {
Поправил все замечания

2024-03-08 12:10 UTC, merged