hw2 PR
martynovvladislav/tinkoff-java-backend-course-2024 pull request #2
Opened 2024-02-19 20:52 UTC by martynovvladislav

Созданы клиенты GitHubClient и StackOverflowClient для получения информации об обновлениях страницы через api.
Добавлены тесты WireMock
Добавлен класс LinkUpdateScheduler для периодической проверки обновлений страницы (пока что заглушка в виде логирования)

2024-03-07 16:00 UTC, edikgoose requested changes
Все хорошо, советую:
- Почитать про retry и timeout и как их использовать в клиенте. Также в целом про паттерны отказоустойчивости. Будет полезным для собесов
-  Добавить конфигурацию для клиентов в конфиг и вынести параметры в env. Должно получиться что-то типо такого:
```yaml
web-client:
    github:
        base-url: ${GITHUB_BASE_URL:https://...}
        read-timeout: ${GITHUB_READ_TIMEOUT:1000}
        write-timeout: ${GITHUB_WRITE_TIMEOUT:1000}
        retry-count: ${GITHUB_RETRY_COUNT:5}
    stackoverflow:
        base-url: ... (the same)
```
то, что указано после двоеточия, будет использоваться, если env параметр не задан. То есть это дефолтное значение

Задание сделано, тесты есть
6/6

2024-03-07 16:00 UTC, edikgoose commented on scrapper/src/main/java/edu/java/github/GitHubReposClient.java
> +        this.webClient = WebClient.builder().baseUrl(DEFAULT_URL).build();
лучше методы билдера на разных строчках писать

2024-03-07 16:00 UTC, edikgoose commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubReposClient();
Очень советую получать base-url из application.yaml файла и передавать сюда. Нужно для того, чтобы ты мог быстро передплоить свое приложение просто поменя env параметр и не залезая в код

2024-03-07 16:00 UTC, edikgoose commented on scrapper/src/main/java/edu/java/github/ReposResponse.java
> +    @JsonProperty("id") Long id,
А без @JsonProperty jackson не конвертит?

2024-03-07 16:00 UTC, edikgoose commented on scrapper/src/test/java/edu/java/scrapper/clients/GitHubClientTest.java
> +        WireMock.configureFor("localhost", wireMockServer.port());
Есть аннотация @WireMockTest(httpPort = 8080), будет поудобнее)

2024-03-08 12:24 UTC, martynovvladislav commented on scrapper/src/main/java/edu/java/github/ReposResponse.java
> +    @JsonProperty("id") Long id,
Я видел такой способ на семинаре или лекции, решил использовать. Без Property тесты валятся.

2024-03-08 12:51 UTC, martynovvladislav commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new GitHubReposClient();
Замечания подправил, с получением из yaml файла тоже поработаю в коммитах следующих домашек

2024-03-08 13:22 UTC, merged

2024-03-10 16:17 UTC, edikgoose commented on scrapper/src/main/java/edu/java/github/ReposResponse.java
> +    @JsonProperty("id") Long id,
Странно, можешь описать проблему и в чате спросить