hw3 PR
martynovvladislav/tinkoff-java-backend-course-2024 pull request #3
Opened 2024-03-03 15:41 UTC by martynovvladislav

2024-03-10 16:19 UTC, edikgoose requested changes
Все ок, поправь замечаний и будет пушка
Единственное, что не увидел тестов на контроллеры. По хорошему нужно написать. Минус балл за это
И доработай плиз получения всех параметров из yaml файла. В будущих дз снижу балл, если останется так же.

2024-03-10 16:19 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/clients/ScrapperClientImpl.java
> +    private final static String DEFAULT_URL = "http://localhost:8080";
static обычно до final идет

2024-03-10 16:19 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/clients/ScrapperClientImpl.java
> +        this.webClient = WebClient.builder().baseUrl(url).build();
Я вижу ты более менее шаришь, поэтому советую почитать про более декларативный подход
https://www.baeldung.com/spring-6-http-interface
Избавит от boilerplate кода

2024-03-10 16:19 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/controllers/ExceptionController.java
> +public class ExceptionController {
Вообще это ExceptionHandler и я бы его переместил в exception пакет

2024-03-10 16:19 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/dtos/AddLinkRequest.java
> +public class AddLinkRequest {
Советую добавить Dto в конце имени во всех классах. Так будет проще читать код, когда проект разрастется

2024-03-10 16:19 UTC, edikgoose commented on bot/src/main/java/edu/java/bot/exceptions/ChatDoesNotExistException.java
> +public class ChatDoesNotExistException extends Exception {
Уверен, что CheckedException это хорошая идея?)
Я бы использовал RuntimeException

2024-03-10 16:19 UTC, edikgoose commented on scrapper/src/main/java/edu/java/scrapper/clients/bot/BotClientImpl.java
> +    private final static String DEFAULT_URL = "http://localhost:8090";
Не очень это нравится. Все значения урлов и подобных вещей должны быть заданы в application.yaml файле, чтобы их можно было просто поменять, не залезая в код. Даже дефолтные

2024-03-10 16:19 UTC, edikgoose commented on scrapper/src/main/java/edu/java/scrapper/controllers/ScrapperController.java
> +public class ScrapperController {
Я бы разделил их на два контроллера: LinkController и ChatController

2024-03-10 22:57 UTC, martynovvladislav commented on scrapper/src/main/java/edu/java/scrapper/clients/bot/BotClientImpl.java
> +    private final static String DEFAULT_URL = "http://localhost:8090";
Занимаюсь этим. Правильно понимаю, что нужен отдельный конфиг класс для этого создавать?

2024-03-11 09:03 UTC, edikgoose commented on scrapper/src/main/java/edu/java/scrapper/clients/bot/BotClientImpl.java
> +    private final static String DEFAULT_URL = "http://localhost:8090";
желательно да

2024-03-11 11:23 UTC, martynovvladislav commented on scrapper/src/main/java/edu/java/scrapper/clients/bot/BotClientImpl.java
> +    private final static String DEFAULT_URL = "http://localhost:8090";
С этим разобрался. Еще вопрос, а у контроллеров нужно тестировать просто коды возврата? Данных еще нет, у меня там просто заглушки

2024-03-21 12:14 UTC, merged